--- 
title: "Guía para usar Haver Analytics"
author: "Victor Cuspinera"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Guía para usar Haver Analytics, enfocándose en las series relacionadas con el dinero en efectivo y herramientas que podrían ser útiles a la Oficina de Estadística de la Dirección General de Emisión del Banco de México."
---

# Introducción {#intro}

@haver es una empresa que se encarga de coleccionar información económica, financiera y monetaria, a nivel global de distintas fuentes oficiales. 

El @haver_banxico tiene contratado una subscripción a algunas de las bases de datos de esta empresa, por lo que cualquier trabajador del banco puede solicitar el acceso a esta información sin incurrir en costo adicional alguno.

Algunas de las bases que se tienen contratadas son:

1. U.S. ECONOMIC STATISTIC (USECON). Estadísticas económicas y financieras básicas de Estados Unidos, actualizadas a pocos minutos del lanzamiento.

3. COUNTRY SUMMARY STATISTICS (G10+). Indicadores macroeconómicos y financieros de países desarrollados  como Estados Unidos, Canadá, Unión Europea, Japón, Australia y Nueva Zelanda.

4. COUNTRY SUMMARY STATISTICS (EMERGE). Indicadores macroeconómicos y financieros para más de 80 países de mercados emergentes.

5. LATIN AMERICAN MACROECONOMIC DATA (EMERGELA). Información económica y financiera para 16 países de América Latina. 

6. CENTRAL & EASTERN EUROPE and WESTERN ASIA (EMERGECW). Información económica y financiera de 24 países de Europa del Este, Central y países de Asia occidental.

7. MIDDLE EAST and AFRICAN EMERGIN MARKETS (EMERGEMA). Información económica y financiera para 26 países de Oriente Medio y los países africanos.

8. ASIA/PACIFIC RIM EMERGING MARKETS (EMERGERPR). Información económica y financiera para 15 economías en Asia-Pacífico.

9. FOCUS ECONOMIC CONSENSUS. Información histórica sobre expectativas de indicadores económicos para una variedad de economías.


[Da click aquí](http://webinterno/centro-de-informacion-electronica/acceso-a-recursos-electronicos/bases-de-datos-con-informacion-estadistica/haver-analytics-global/haver-analytics-global--.html) para revisar con mayor detalle los servicios contratados por Banxico a Haver Analytics.


## Salvedad de uso
⚠ El contenido de este documento interno, así como las conclusiones que de éste se deriven, son responsabilidad exclusiva del autor y no reflejan necesariamente las del Banco de México.
